version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    depends_on:
      - kafka
      - redis
    ports:
      - "8000:8000"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      REDIS_URL: redis://redis:6379/0
      JWT_SECRET: ${JWT_SECRET:-change_me_in_production}

  ingestion:
    build:
      context: ./services/ingestion
      dockerfile: Dockerfile
    container_name: ingestion
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      REDIS_URL: redis://redis:6379/0
      JWT_SECRET: ${JWT_SECRET:-change_me_in_production}
      INPUT_PATH: /data/events.jsonl
      USER_ACTIVITY_TOPIC: user_activity
    volumes:
      - ./tmp_cert:/data

  ml-engine:
    build:
      context: ./services/ml-engine
      dockerfile: Dockerfile
    container_name: ml-engine
    depends_on:
      - kafka
      - redis
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      REDIS_URL: redis://redis:6379/0
      JWT_SECRET: ${JWT_SECRET:-change_me_in_production}
      PROCESSED_TOPIC: processed_features
      ANOMALY_TOPIC: anomaly_scores
    volumes:
      - ./tmp_cert/model_artifacts:/models

  risk-scoring:
    build:
      context: ./services/risk-scoring
      dockerfile: Dockerfile
    container_name: risk-scoring
    depends_on:
      - kafka
      - redis
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      REDIS_URL: redis://redis:6379/0
      JWT_SECRET: ${JWT_SECRET:-change_me_in_production}
