"""
Email notifier — sends HTML alert emails via SMTP (aiosmtplib).

The email body contains a formatted version of the XAI report with
the executive summary, feature importance table, and investigation
steps rendered as HTML.
"""

from __future__ import annotations

import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any

from app.config import get_settings
from app.models import Alert

logger = logging.getLogger(__name__)
settings = get_settings()


def _build_html(alert: Alert, xai_report: dict[str, Any]) -> str:
    """Render the XAI report as an HTML email body."""
    sections = xai_report.get("sections", [])

    html_parts: list[str] = [
        "<html><body>",
        '<div style="font-family: Arial, sans-serif; max-width: 700px;">',
        f'<h1 style="color: {"#d32f2f" if alert.risk_level == "CRITICAL" else "#f57c00"};">'
        f"⚠️ Insider Threat Alert — {alert.risk_level}</h1>",
        "<table>",
        f"<tr><td><b>User:</b></td><td>{alert.user_id}</td></tr>",
        f"<tr><td><b>Risk Score:</b></td><td>{alert.risk_score:.2f}</td></tr>",
        f"<tr><td><b>Anomaly Type:</b></td><td>{alert.anomaly_type}</td></tr>",
        f"<tr><td><b>Status:</b></td><td>{alert.status}</td></tr>",
        "</table>",
        "<hr>",
    ]

    for sec in sections:
        html_parts.append(f"<h2>{sec['title']}</h2>")
        html_parts.append(f"<p>{sec.get('content', '')}</p>")

        # Detector table
        if "detectors" in sec:
            html_parts.append(
                '<table border="1" cellpadding="4" cellspacing="0">'
                "<tr><th>Detector</th><th>Score</th><th>Anomaly?</th><th>Detail</th></tr>"
            )
            for d in sec["detectors"]:
                flag = "✓" if d["is_anomaly"] else "✗"
                html_parts.append(
                    f"<tr><td>{d['detector']}</td><td>{d['anomaly_score']:.4f}</td>"
                    f"<td>{flag}</td><td>{d['key_detail']}</td></tr>"
                )
            html_parts.append("</table>")

        # Feature ranking
        if "features" in sec:
            html_parts.append(
                '<table border="1" cellpadding="4" cellspacing="0">'
                "<tr><th>Rank</th><th>Feature</th><th>Importance</th><th>Source</th></tr>"
            )
            for f in sec["features"]:
                html_parts.append(
                    f"<tr><td>{f['rank']}</td><td>{f['feature']}</td>"
                    f"<td>{f['importance']:.4f}</td><td>{f['source']}</td></tr>"
                )
            html_parts.append("</table>")

        # Baseline comparisons
        if "comparisons" in sec:
            html_parts.append("<ul>")
            for c in sec["comparisons"]:
                html_parts.append(f"<li>{c}</li>")
            html_parts.append("</ul>")

        # Steps
        if "steps" in sec:
            html_parts.append("<ol>")
            for s in sec["steps"]:
                # Strip leading number + dot
                text = s.lstrip("0123456789. ")
                html_parts.append(f"<li>{text}</li>")
            html_parts.append("</ol>")

    html_parts.append(
        '<p style="color: #888; font-size: 12px;">'
        "Generated by ITDS XAI Engine</p>"
    )
    html_parts.append("</div></body></html>")
    return "\n".join(html_parts)


async def send_email(
    alert: Alert,
    xai_report: dict[str, Any],
) -> bool:
    """
    Send an HTML alert email via SMTP using aiosmtplib.

    Returns True on success, False on failure.
    """
    if not settings.SMTP_HOST:
        logger.warning("smtp_not_configured")
        return False

    try:
        import aiosmtplib
    except ImportError:
        logger.warning("aiosmtplib_not_installed — email notifier disabled")
        return False

    msg = MIMEMultipart("alternative")
    msg["Subject"] = (
        f"[ITDS {alert.risk_level}] Alert for {alert.user_id} — "
        f"score {alert.risk_score:.2f}"
    )
    msg["From"] = settings.EMAIL_FROM
    msg["To"] = ", ".join(settings.EMAIL_TO)

    # Plain-text fallback (XAI markdown)
    md = xai_report.get("markdown", alert.summary)
    msg.attach(MIMEText(md, "plain"))

    # HTML body
    html = _build_html(alert, xai_report)
    msg.attach(MIMEText(html, "html"))

    try:
        await aiosmtplib.send(
            msg,
            hostname=settings.SMTP_HOST,
            port=settings.SMTP_PORT,
            username=settings.SMTP_USER or None,
            password=settings.SMTP_PASSWORD or None,
            use_tls=settings.SMTP_USE_TLS,
        )
        logger.info("email_notification_sent", extra={"alert_id": str(alert.id)})
        return True
    except Exception:
        logger.exception("email_notification_error", extra={"alert_id": str(alert.id)})
        return False
